name: CI
on:
    push:
        branches:
            - "**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: "pnpm"

            - name: Install dependencies
              run: |
                  npm install -g pnpm
                  pnpm install --frozen-lockfile

            - name: Run lint and build
              run: |
                  pnpm run lint
                  pnpm run build
                  pnpm run build
