name: Publish
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"  
          registry-url: https://registry.npmjs.org  
      - name: Log in to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_SUE_TOKEN }}" > ~/.npmrc
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm install --frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.TAFkEET_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SUE_TOKEN }}
      -  run: |
          pnpm config set registry https://npm.pkg.github.com
          pnpm set //npm.pkg.github.com/:_authToken ${{ env.NODE_AUTH_TOKEN }}
          pnpm run release
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
